language: php

php:
  - 5.3
  - 5.4

services:
  - rabbitmq

before_script:
  - composer install --dev --prefer-source

script: phpunit --coverage-text

notifications:
  email:
    - benjamin.dulau@gmail.com
